### PR TITLE
Factories simple to ridiculous

### PR DESCRIPTION
**Pull request by IanWhitney**
New post here: http://designisrefactoring.com/2016/02/03/factories/

### CODE REVIEW

**Comment by dreyks** [comment]
``` ruby
Campus.subclasses.detect(->{UnknownCampus.new}) { ...skip... }.new
```

should be `->{UnknownCampus}` without `new`. Otherwise You'll get `new` called twice

**Comment by IanWhitney** [comment]
@dreyks Thanks for spotting that! Fixing it now.

**Comment by roryokane** [comment]
More comments are on [this story’s post on Lobsters](https://lobste.rs/s/swkm57/factories).

**Comment by roryokane** [comment]
Here is another solution – creating a class `AbbreviatedCampuses` that all campuses register themselves with using `AbbreviatedCampuses.register self`. All campuses also implement an `abbreviation` method as the single place their abbreviation is written.

With this method, when you add a new campus, you only need to change one place in the code. But you don’t have to do the slow and hard-to-understand metaprogramming with `ObjectSpace` or `Object.const_get` – you explicitly link the new campus to the new registry. And the registration line in each campus class is shorter than the three-line `self.campus_like?` definition with the `ObjectSpace` solution.

``` ruby
class UnknownCampus
  def name
    "Unknown Campus"
  end

  def mascot
    "Unknown Mascot"
  end
end

class AbbreviatedCampuses
  @@campus_like_classes = Hash.new(UnknownCampus)

  def self.register(klass)
    abbreviation = klass.new.abbreviation
    @@campus_like_classes[abbreviation] = klass
  end

  def self.build_from(abbreviation)
    @@campus_like_classes[abbreviation].new
  end
end

# The above two classes must be loaded first.
# The rest can load in any order.

class CampusDetails
  def campus_name(abbreviation)
    AbbreviatedCampuses.build_from(abbreviation).name
  end

  def campus_mascot(abbreviation)
    AbbreviatedCampuses.build_from(abbreviation).mascot
  end
end

class UMNTC
  def name
    "University of Minnesota Twin Cities"
  end
  def mascot
    "Gopher"
  end
  def abbreviation
    "UMNTC"
  end

  AbbreviatedCampuses.register self
end

class UMNMO
  def name
    "University of Minnesota Morris"
  end
  def mascot
    "Cougar"
  end
  def abbreviation
    "UMNMO"
  end

  AbbreviatedCampuses.register self
end

class UMNCR
  def name
    "University of Minnesota Crookston"
  end
  def mascot
    "Golden Eagle"
  end
  def abbreviation
    "UMNCR"
  end

  AbbreviatedCampuses.register self
end

class UMNTCRO
  def name
    "University of Minnesota Rochester"
  end
  def mascot
    "Raptor"
  end
  def abbreviation
    "UMNTCRO"
  end

  AbbreviatedCampuses.register self
end

class CollegeInTheSchools
  def name
    "College in the Schools"
  end
  def mascot
    ""
  end
  def abbreviation
    "CITS"
  end

  AbbreviatedCampuses.register self
end
```

Some sample test code:

``` ruby
puts CampusDetails.new.campus_name("CITS")
puts CampusDetails.new.campus_mascot("UMNTCRO")
puts CampusDetails.new.campus_mascot("NOSUCH")
```

I think the two `CampusDetails` methods would be better off as class methods, defined like `def self.campus_name`, since they don’t have any instance variables. But I kept them instance methods in this solution for easy comparison.

**Comment by roryokane** [comment]
Also, if all you need from your campuses is to get their data, you could just use a Hash instead.

Though this solution doesn’t support custom class behavior, it’s a lot simpler and more concise. This solution could apply before the step in your article when you add the `CollegeInTheSchools` class, which is presumed to have additional behavior. 

``` ruby
class CampusDetails
  CAMPUS_LIKES_BY_ABBR = {
    "UMNTC" => {
      name: "University of Minnesota Twin Cities",
      mascot: "Gopher",
    },
    "UMNMO" => {
      name: "University of Minnesota Morris",
      mascot: "Cougar",
    },
    "UMNCR" => {
      name: "University of Minnesota Crookston",
      mascot: "Golden Eagle",
    },
    "UMNTCRO" => {
      name: "University of Minnesota Rochester",
      mascot: "Raptor",
    },
    "CITS" => {
      name: "College in the Schools",
      mascot: "",
    },
  }
  CAMPUS_LIKES_BY_ABBR.default = {
    name: "Unknown Campus",
    mascot: "Unknown Mascot",
  }

  def campus_name(abbreviation)
    CAMPUS_LIKES_BY_ABBR[abbreviation][:name]
  end

  def campus_mascot(abbreviation)
    CAMPUS_LIKES_BY_ABBR[abbreviation][:mascot]
  end
end
```

**Comment by IanWhitney** [comment]
@roryokane The hash is a fine approach and probably one I'd use in some cases. I tend towards using objects over data structures in most cases, and since the post was about factories the hash approach didn't really fit.

The `AbbreviatedCampuses.register self` option is not one I'd ever thought of. Thank you for pointing it out. My brain doesn't think of doing method calls like that inside of class definitions.

**Comment by IanWhitney** [comment]
Also, thanks for the PRs, @roryokane. They have been pushed to the site. The nice thing about writing [examples in Rust](http://designisrefactoring.com/2015/12/30/simple-rust-part-four/) is that I have tooling that will tell me if the code is correct. With Ruby I'm usually just freehanding it and occasionally checking syntax in IRB. So I make some dumb mistakes, as you noticed.

**Pull request merged**
